// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAGHjbnVmOFwBkoG9_TPcbZhyJAo6k5Wg',
    appId: '1:1052144612625:web:0a48f3f52c6eb5c26c88b0',
    messagingSenderId: '1052144612625',
    projectId: 'appcolor-ff784',
    authDomain: 'appcolor-ff784.firebaseapp.com',
    storageBucket: 'appcolor-ff784.appspot.com',
    measurementId: 'G-GPR81MHXMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwH_e_U39YN_T_RH9Th7rIJpHMBqPoqfY',
    appId: '1:1052144612625:android:bbda161fae4abddf6c88b0',
    messagingSenderId: '1052144612625',
    projectId: 'appcolor-ff784',
    storageBucket: 'appcolor-ff784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcIpJDqAkLsew0KsveW1HchZMlFajJBGA',
    appId: '1:1052144612625:ios:0b6b5dbcd469faa86c88b0',
    messagingSenderId: '1052144612625',
    projectId: 'appcolor-ff784',
    storageBucket: 'appcolor-ff784.appspot.com',
    iosBundleId: 'com.example.appPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcIpJDqAkLsew0KsveW1HchZMlFajJBGA',
    appId: '1:1052144612625:ios:d93e5b0a7eb799486c88b0',
    messagingSenderId: '1052144612625',
    projectId: 'appcolor-ff784',
    storageBucket: 'appcolor-ff784.appspot.com',
    iosBundleId: 'com.example.appPrueba.RunnerTests',
  );
}
